author           = cool_beans
depends          = default, dye
description      = Try to rip off your friends with counterfeit diamonds and other precious materials available through the forgery workbench.
name             = fakery
optional_depends = basic_materials, lavastuff, cloud_items, moreores, overpowered, appliances, pipeworks, technic, ia_util
title            = IA Fakery
